apiVersion: apps/v1
kind: Deployment
metadata:
  name: clockdegree
  labels:
    app: clockdegree
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clockdegree
  template:
    metadata:
      labels:
        app: clockdegree
    spec:
      containers:
        - name: clockdegree
          image: app-image1:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 30
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: clockdegree
spec:
  selector:
    app: clockdegree
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
