apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: default
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch: {}
      memory_limiter:
        limit_mib: 512
        spike_limit_mib: 128
        check_interval: 1s

    exporters:
      otlp:
        endpoint: "simplest-collector.default.svc.cluster.local:14250"
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp]

