apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: clockdegree
  namespace: default
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: clockdegree
  endpoints:
    - port: http
      path: "/actuator/prometheus"
      interval: 5s
